export { default as Main } from './chat'
export { default as Error } from './error'
export { default as Login } from './login'
export { default as Signup } from './signup'
export { default as Admin } from './admin'
export { default as Dashboard } from './dashboard'
export { default as Forgot } from './forgot'